### ISSUE TITLE
#[cfg(test)] args are not IDE friendly

### ISSUE THREAD

**Issue by breezewish** [tikv/minitrace-rust#101]
With latest intellij-rust (14 Feb 2022), the IDE doesn't work well for such functions:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/1916485/156522409-319e00b3-c6c5-4b57-9ef9-fb7f0393365f.png">

**Comment by Xuanwo** [comment]
How about making it a new function like:

```rust
#[cfg(test)]
pub fn root_with_collect(event: &'static str, collect: GlobalCollect) -> (Self, Collector) {}
```

**Comment by taqtiqa-mark** [comment]
Collating functions similarly affected:

- [ ] `root`
- [ ] [`enter_with_local_parent`](https://github.com/tikv/minitrace-rust/blob/52891cc0deef525601220ff1d55649d40542ae63/minitrace/src/span.rs#L90)
