### ISSUE TITLE
Incremental batch vs Bulk one-shot upload

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#111]
Thank you for your effort in making minitrace.  And for making it open source.

Is batch uploading to the Jaeger instance possible?

AFAICT all spans are held in memory and then a bulk upload in one-shot is done.  
Is that understanding correct?

If so is there any guard-rail for the amount of memory that can be used

**Comment by andylokandy** [comment]
Batching has been implemented in #153
