### ISSUE TITLE
Doc: Correct/clarify when `set_local_parent()` is required and when not

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#115]
> Before starting a LocalSpan, a scope of parent span should be set using [Span::set_local_parent()](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.set_local_parent). Use [LocalSpan::enter_with_local_parent()](https://docs.rs/minitrace/latest/minitrace/local/struct.LocalSpan.html#method.enter_with_local_parent) to start a LocalSpan, and then, it will become the new local parent.

> If no local parent is set, the `enter_with_local_parent()` will do nothing.

However, the [`asynronous` example](./minitrace/examples/asynchronous.rs) does **not** invoke `Span::set_local_parent()`, and yet it works i.e. does not 'do nothing'.

**Comment by andylokandy** [comment]
It's because [`in_span`](https://docs.rs/minitrace/latest/minitrace/future/trait.FutureExt.html#method.in_span) does set the local parent for the inner future:

> Besides, it will set the span as the local parent at every poll so that LocalSpan becomes available inside the future. Under the hood, it call [Span::set_local_parent](https://docs.rs/minitrace/latest/minitrace/struct.Span.html#method.set_local_parent) when the executor [poll](https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html#tymethod.poll) it.

**Comment by andylokandy** [comment]
Updated doc in https://github.com/tikv/minitrace-rust/pull/153
