### ISSUE TITLE
Doc: Minitrace goals regarding Logging and Tracing crate compatibility with debug! etc macros

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#116]
It would be nice to know the scope and goals of the maintainers, with respect to compatibility with the Logging/Tracing crate ecosystems.

My preference is to place compatibility as a secondary goal, with the requirement that any compatibility does not adversely impact performance.

Specifically, here I'll address the provision of macro functions such a `debug!(...), warn!(...)`, etc.

My 2c: 
The minitrace overhead is sufficiently low that, if users find it useful to have:

```rust
fn mine() {
    ...
    server.start();
    debug!("server instance started")
    ...
}
``` 

They could be encouraged to add the `#[trace]` attribute to the `start` function.  In cases where `start` is defined in a 3rd-party crate, I'd advocate guiding user to adopt a "new-function" idiom/pattern that is a counterpart to the ["new-type"]() pattern.

Where by we could say something like: Tracing your usage of third-party crates using a "new-function" idiom/pattern, gives compile time guarantees that the function start/entry and end/exit times are visible.  The previous example would become:

```rust
fn mine(){
    ...
    start(server);
    ...
}

#[trace("server-start")]
fn start(server: Server){
    server.start;
}

**Comment by andylokandy** [comment]
Has been documented in readme https://github.com/tikv/minitrace-rust#how-does-minitrace-differ-from-other-tracing-libraries
