### ISSUE TITLE
Doc: block expression requirement

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#125]
The documentation is **entirely silent** on the fact that block expressions are an absolute requirement for setting up spans ***in addition to*** the `#[trace]` attribute.

**Comment by andylokandy** [comment]
The records of `LocalSpan` are submitted to the collector once the guard of `set_local_parent` gets dropped. So, if you collect the trace when the guard is alive, the `LocalSpan` will have no chance to get collected. And yes, we need to update the document for this behavior.
