### ISSUE TITLE
Bug: Empty functions are not expanded

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#129]
This arose in the course of populating integration test suite related to #113.

The following survive untouched:

```rust
#[trace]
async fn empty_async() {}

#[trace]
fn empty_sync() {}
```

**Comment by taqtiqa-mark** [comment]
@andtlokandy, I'm finding quite a lot of these corner cases.... given I'm in the midst of migrating the proc-macro code to the new pipeline structure, I wonder if the least painful path forward won't be to wait until that pipeline refactor lands.

Otherwise I suspect someone faces merge-hell in trying to resolve the pipeline code with these subtle issues fixes.

Thoughts?

**Comment by andylokandy** [comment]
How long will the pipeline refactoring take? Since such subtle cases rarely exist in a practical project (let's say TiKV and RisingLightDB), I think it's not too urgent to fix.

**Comment by taqtiqa-mark** [comment]
> PS: If I didn't get it wrong, the pipeline refactoring could fix those problems, right?

It might... depends on how subtle the edge cases are.  Some others I see now are very subtle.

**Comment by taqtiqa-mark** [comment]
> How long will the pipeline refactoring take?

Rust's limited integration test support is proving the sticking point.  I'm on architecture-attempt #3 to see if I can make it work.

Weeks not months?

**Comment by taqtiqa-mark** [comment]
Voided by PR #127 rejection.
