### ISSUE TITLE
Feature: #[trace(variables = [b])]

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#135]
Another use case to take into account while the model phase of https://github.com/tikv/minitrace-rust/issues/113 is taking shape.....

This is also related to the #134 use case, but not limited to:

- aiding a new/infrequent user quickly get useful data to assist with debugging.
- 'tracing' the LHS of the expression where the function is in a sealed trait or 3rd-party crate. 

The following should be possible (initially sync only):

```rust
#[trace(variables=[p, n]]
fn factorial(mut n: u64) -> u64 {
    let mut p = 1;
    while n > 1 {
        p *= n;
        n -= 1;
    }
    p
}
```

The idea would be to have this become (better suggestions welcome):

```rust
fn factorial(mut n: u64) -> u64 {
    let _g = LocalSpan::enter_with_local_parent();
    let mut p;
    {
            let _mt = LocalSpan::enter_with_local_parent();
            p = 1;
    }
    while n > 1 {
        {
            let _mt = LocalSpan::enter_with_local_parent();
            p *= n;
        }
        {
            let _mt = LocalSpan::enter_with_local_parent();
            n -= 1;
        }
    }
    p
}
```

Producing SpanRecords for:

 - p = 1
 - p = 8
 - n = 7
 - p = 56
 - n = 6

**Comment by andylokandy** [comment]
Implemented in https://github.com/tikv/minitrace-rust/pull/150. Refer to [example](https://github.com/tikv/minitrace-rust/blob/master/minitrace/examples/log.rs)

**Comment by taqtiqa-mark** [comment]
I don't see where in that example you get the variable tracing from `#[trace(variables=[p, n]]`.

**Comment by andylokandy** [comment]
Oh my bad, I thought it should only records function arguments and return values like like the log_derive. However, even if such instrument in code is possible, it could be better added to log_derive.

**Comment by taqtiqa-mark** [comment]
Isn't this categorically different when the RHS is a 3rd party crate, and more so if it uses minitrace.  Will the result really be the same?

**Comment by andylokandy** [comment]
It's not the same as using log_derive, what I proposed is to add such feature to log_derive. And because minitrace could work seamlessly with log, it will eventually the same as implementing such feature in minitrace.

**Comment by taqtiqa-mark** [comment]
OK, I need to become more familiar with log_derive.

**Comment by andylokandy** [comment]
The log_derive crate appears to have been unmaintained for some time and is not compatible with async-trait. It might be feasible to consider a successor crate.

**Comment by andylokandy** [comment]
FYI, I've made an experimental crate [logcall](https://github.com/andylokandy/logcall) for async-trait compatibility by some simple changes on current minitrace-macro implementation.

**Comment by taqtiqa-mark** [comment]
Sorry to keep pushing back on this closure. In the OP I provided a sketch of the tracing that would be injected.  Could you similarly provide the tracing logic that would apply to the given example for the approach you advocate?
