### ISSUE TITLE
does not work in a thread

### ISSUE THREAD

**Issue by MarkSwanson** [tikv/minitrace-rust#164]
minitest works fine in my app, but not in a thread.
        let join_handle = thread::Builder::new().name("blah_thread".to_string()).spawn(move || {
            let parent = SpanContext::random();
            let root = Span::root("iio_thread", parent);
            let _g = root.set_local_parent();
            minitrace::Event::add_to_local_parent("blah()", || [("blah".into(), "blah".into())]);

The blah Event is never logged. Why is that?

**Comment by andylokandy** [comment]
Could you provide a complete minimal-reproducible example?
