### ISSUE TITLE
Request: panic instead of noop

### ISSUE THREAD

**Issue by MarkSwanson** [tikv/minitrace-rust#166]
I've spent a few hours trying many combinations of spans, localspans but no threads that use minitrace have their spans or events logged. I also get strange warnings in the jaeger web app like: invalid parent span IDs
I was hoping that minitrace::flush() would help, but it does not.
The futures I created do log, but they create their own root and this isn't really what I want.
I was hoping that if minitrace would panic instead of return noop then I could get some feedback for when I was using the API incorrectly.
Currently minitrace seems to just silently hide API usage errors.
Maybe what might help as well is if there was some way to manually flush all spans that have data queued to be written. This wouldn't help with the API misuse, but it would help me debug the 'silently hide API misuse' problems as I'd be able to see what has been silently disregarded.
Thanks!

**Comment by andylokandy** [comment]
could you provide a complete example where you meet the problem?

**Comment by andylokandy** [comment]
Mind that the root span should cover all of its children spans. You may drop the root span too early.

Closing until we've further information.
