### ISSUE TITLE
`minitrace-opentelemetry` doesn't work with `opentelemetry_zipkin` exporter

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#182]
Seems like using `opentelemetry_otlp` works great (https://github.com/tikv/minitrace-rust/tree/master/minitrace-opentelemetry), but when an exporter from `opentelemetry_zipkin` (https://crates.io/crates/opentelemetry-zipkin) is in use, seems like the global collector expects a tokio runtime to be available, and fails with:

```
thread 'minitrace-global-collector' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

This is how I configured the reporter and exporter: 

```
let exporter = opentelemetry_zipkin::new_pipeline()
          .with_service_name(service_name)
          .with_collector_endpoint(endpoint)
          .init_exporter()?;

let reporter = OpenTelemetryReporter::new(exporter,  SpanKind::Server, resource, lib);
```

I assume it might be related to the fact that

**Comment by andylokandy** [comment]
Do you have a tokio runtime initialized when creating the zipkin reporter?

**Comment by andylokandy** [comment]
opentelemetry community is sort of mess at this moment... while opentelemetry_jaeger must be used in a environment without tokio, opentelemetry_zipkin requires the opposite.. But anyway I do have workaround: make a Reporter wrapper who ensure that a tokio runtimr exists and call inner reporter afterwards.

**Comment by dotansimha** [comment]
> Do you have a tokio runtime initialized when creating the zipkin reporter?

I am using `actix` as web server, and it's a wrapper around `tokio`, so yeah I do have one. 



> opentelemetry community is sort of messy at this moment... while opentelemetry_jaeger must be used in a environment without tokio, opentelemetry_zipkin requires the opposite.. But anyway I do have workaround: make a Reporter wrapper who ensure that a tokio runtimr exists and call inner reporter afterwards.

I agree it's kinda it's in a mess, but the recent changes of providing the `Runtime` to each `SpanProcessor` kinda makes sense (also related: https://github.com/tikv/minitrace-rust/issues/179#issuecomment-1905444050). 
I can create a processor that uses async runtime, or not. 

I prefer the `Reporter` trait and it's simplicity, and it might be easier to implement a "native" minitrace exporter for Zipkin, instead of using the opentelemetry_rust one.
