### ISSUE TITLE
Feature request: Span property on #[trace] macro

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#183]
I was wondering if this could be a nice enhancement to have the option to define `Span` properties as part of the `#[trace]` macro? Something like: 

```
// name can remain a special property 
#[trace(name = "my_fn", my_prop = "value"]
fn my_fn() {}

#[trace(my_prop = "value"]
fn my_fn() {}
```

This seems to be nice, because the alternative is to define the `Span` manually inside the function and add the properties.

**Comment by andylokandy** [comment]
Seems a feature good to have. But the property on macro can only contains static str. For calculated property, minitrace had a `LocalSpan::add_property` to local parent, which was then replaced by `Event`. Maybe it'll be nice to add `LocalSpan::add_property` back.

**Comment by dotansimha** [comment]
> Seems to be a feature good to have. But the property on macro can only contains static str. 

Yeah, that makes perfect sense. My use case is for adding static properties. For dynamic properties, I'm constructing the Span manually (without the macro) and then add my dynamic properties. 

> For calculated property, minitrace had a `LocalSpan::add_property` to local parent, which was then replaced by `Event`. Maybe it'll be nice to add `LocalSpan::add_property` back.
> 
> Which one is more suitable for your case? `LocalSpan::add_property` or `Event`?

`Event` feels like is has a different use case, because I might want to add there some in-depth detailing. 

The `LocalSpan::add_property` might also work great, I assume it allows me to access the span created by the `trace` macro?

**Comment by andylokandy** [comment]
I've some ideas on the macro syntax:

```rust
#[trace(name = "test-span"; "k" = "v", "a" = "{a:?}")]
fn f(a: u32) -> u32 {
    a
}

#[trace(name = "test-span", "k" = "v", "a" = "{a:?}" )]
fn f(a: u32) -> u32 {
    a
}

#[trace(name = "test-span", property("k" = "v", "a" = "{a:?}"))]
fn f(a: u32) -> u32 {
    a
}

#[trace(name = "test-span"))]
fn f(a: u32) -> u32 {
    LocalSpan::add_properties(|| [("k", "v"), ("a", format!("{a:?}"))]);   // not adding new syntax to macro
    a
}
```

What do you think? @zhongzc

**Comment by zhongzc** [comment]
I don't have any opinions in general, but I'd also like to suggest an interesting option:

```rust
#[trace(
    name = "test-span",
    properties = {"k": "v", "a": "{a:?}"}
)]
fn f(a: u32) -> u32 {
    a
}
```

**Comment by dotansimha** [comment]
Yeah, I think the more explicit way of using `properties = { ... }` is more readable.
