### ISSUE TITLE
Panic on wasm: time not implemented on this platform

### ISSUE THREAD

**Issue by andylokandy** [tikv/minitrace-rust#187]
> I gave it a spin and it seems to fail at runtime: `time not implemented on this platform` (on WASM runtime). 
>
> All I did so far it to add `minitrace` with `features = ["enable"]` and did the following at startup:

```
  let collector = LocalCollector::start();
  let result = run_flow(req, env).await;
  let local_spans = collector.collect();
  let parent_context = SpanContext::random();
  let span_records = local_spans.to_span_records(parent_context); // ❗ 
```

> I'm pretty sure this originates in `to_span_records`, because without calling it, it seems to work fine. I printed `local_spans` and it seems to correctly contain the spans 🎉

_Originally posted by @dotansimha in https://github.com/tikv/minitrace-rust/issues/185#issuecomment-1906809996_

**Comment by andylokandy** [comment]
It'll be hard to get timing done without a timer... Do you have any idea? @dotansimha

**Comment by andylokandy** [comment]
> what about https://lib.rs/crates/web-time? @andylokandy

Originally posted by @dotansimha

**Comment by andylokandy** [comment]
Seems good. Would you like to create a PR for adding web-time to minstant? SystemTime is only used in https://docs.rs/minstant/latest/minstant/struct.Anchor.html#method.new

**Comment by dotansimha** [comment]
@andylokandy Sure! https://github.com/dotansimha/minstant

**Comment by andylokandy** [comment]
Closed by https://github.com/tikv/minstant/pull/34
