### ISSUE TITLE
`Reporter::report` should be `async fn`? 🤔 

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#189]
Seems like at the moment, `report` function of the `Reporter` trait is defined as sync `fn`. 

I was wondering if it makes sense to make it `async` and then allow the caller to decide how to handle the `Future`? 

I noticed that some of the existing reporters are using `block_on`, but I think this should be the responsibility of the collector to decide how to handle the `Future`? 🤔 

Context: similar to previous issues, we want to integrate minitrace with a WASM runtime (for CloudFlare Worker), and we can run a `Future` behind the scenes without blocking the response. So ideally, we can take the collected spans and just `report().await` it in the background. 

I'll be happy to open a PR if it makes sense.

**Comment by andylokandy** [comment]
Making report() async will take over control of the runtime from user. I think it'll be opposite to your need.

**Comment by dotansimha** [comment]
> Making report() async will take over control of the runtime from user. I think it'll be opposite to your need.

Hmm, actually that's a good point 🤔 

If I understand correctly, at the moment, I need to use a blocking mechanism to ship the collected traces in the Reporter. Any idea how can I eventually do something like the following?

```
let reporter = make_reporter();
let response = run_flow(req);

// This takes the async function and runs it in "background" (NOT in a thread), so it does not block returning the response
context.wait_until(async move {
   // The function here needs to be async, because wasm-bindgen runtime will convert it to JS Promise and will await it
 
   // Calling the reporter like that means that the reporter must be blocking, right?
   // But even if I want to use `reqwest::blocking` here, it's not supported on WASM runtime. 
   // So ideally, I wanted to `.await` this report call. 
   reporter.report(spans)
}); 

response
``` 

I guess another way to handle it is to kinda do async(wait_until) -> sync (report) -> async (actual HTTP call to ship the traces)? 🤔 not sure how that would look like 🤔

**Comment by andylokandy** [comment]
If you use `LocalCollector`, then the Reporter will not be enabled. Why you need it to work with threads/blocking stuff?

**Comment by dotansimha** [comment]
> If you use `LocalCollector`, the Reporter will not be enabled. Why do you need it to work with threads/blocking stuff?

I have an abstraction on top of the reporter creation. We are building for 2 targets: WASM (CF Worker) and a binary with actix-web HTTP server. This abstraction handles everything, including plugins like tracing/telemetry. 
The only thing left for each runtime is to take care of the tracing lifecycle ( = when to report). 

I guess I can wrap the Reporter somehow and have a different mechanism specifically for the WASM runtime, and then ship it as async. 

Closing ✅
