### ISSUE TITLE
`LocalSpan::enter_with_parent` missing?

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#197]
Seems like `Span::enter_with_parent` exists and works pretty well, but when `LocalSpan` is used, I can only do `enter_with_local_parent`.

My use-case at the moment is related to a previous issue I created here (around WASM support). Seems like `in_span` is only working when `Span` is used, but `Span` is connected to the global collector, so for the WASM runtime I need to use `LocalSpan` only.

@andylokandy any idea if that's missing, or am I doing something wrong?

**Comment by andylokandy** [comment]
Because concurrency is not supported in local span, it's not possible to start a local span whose parent are not the current local parent.

I assume you're interested in tracing a single thread within an asynchronous runtime, correct? Could you describe what kind of results or data you expect to collect from this process?

**Comment by dotansimha** [comment]
> I assume you're interested in tracing a single thread within an asynchronous runtime, correct? Could you describe what kind of results or data you expect to collect from this process?

Yeah, that's exactly what I'm building! A single-threaded (WASM, CF Worker) with async runtime (wasm-bindgen). 

The main issue is that some parts of the codebase are fully agnostic to the runtime, so it's using `Span` and `in_span` for the `Future`s. The main issue is that these are fully ignored when `LocalSpan` and the `LocalCollector` are used. I only get  `SpanRecord`s for traces created by `#[trace]` or `LocalSpan::enter_with_local_parent`.

**Comment by andylokandy** [comment]
Local span can support concurrency but may not be easy... Currently, when a local span exits(drops), the parent of it will become the local parent. We need to add a logical parent to local span that are used to be parent id in SpanRecord, while keeping the real parent unchanged.

**Comment by dotansimha** [comment]
> Local span can support concurrency but may not be easy... Currently, when a local span exits(drops), the parent of it will become the local parent. We need to add a logical parent to local span that are used to be the parent in SpanRecord, while keeping the real parent unchanged.

I see. Any insight on why `#[trace]` does work fine in my case? I'm putting it on `async` functions and it seems to work fine so far 🤔  My current workaround is to split my code to functions and add `#[trace]`.

**Comment by andylokandy** [comment]
could you give a minimun reprodicible example？

**Comment by dotansimha** [comment]
@andylokandy see https://github.com/dotansimha/minitrace-localspan-reproduce 

Basically, I'm facing several issues here (all mentioned in code comments in the repo):
1. I can't use `in_span` (`FutureExt`) with `LocalSpan` for async functions.
2. I can't create `LocalSpan` with an explicit parent (missing `LocalSpan::enter_with_parent`)

**Comment by andylokandy** [comment]
@dotansimha, I've devised an alternative solution. Can you please check if it works for you? Here's the link: https://github.com/tikv/minitrace-rust/pull/201

**Comment by dotansimha** [comment]
> @dotansimha, I've devised an alternative solution. Can you please check if it works for you? Here's the link: #201

Interesting, thanks @andylokandy ! 

So I guess I should use `Span` now just like before? with the new `single-thread` feature enabled? (instead or with `enabled`?)

**Comment by andylokandy** [comment]
You may set both `enable` and `single-thread`, and use `minitrace::flush()` to manually report.
