### ISSUE TITLE
`futures::Stream` and `futures::Sink` instrumentation

### ISSUE THREAD

**Issue by iGxnon** [tikv/minitrace-rust#198]
I am building a network library, using a large number of `Stream`s and `Sink`s to implement IO operations, and preparing to migrate from tokio `tracing` to `minitrace`.

I am wondering if support for `Stream` and `Sink` instrumentation can be added.

A related crate: https://crates.io/crates/tracing-futures

**Comment by andylokandy** [comment]
Yes,this is a good idea!

**Comment by iGxnon** [comment]
I'd like to help :D

**Comment by andylokandy** [comment]
Great to have you on board! Let's delve into the details. You can create a new crate named `minitrace-futures`, and then add `SinkInSpan` and `StreamInSpan`. It can be hosted either in this repository or in a new one of your own, depending on your preference.

**Comment by iGxnon** [comment]
> It can be hosted either in this repository

Yes, I want to put it in this repo.

After considering the generality of the API and its suitability for my own project, I implemented an initial version that meets the needs of my project while also providing more customization for some other scenarios.
Please give me some advice!

https://github.com/iGxnon/raknet-rs/blob/main/src/utils/minitrace.rs

A usecase in my project:

https://github.com/iGxnon/raknet-rs/blob/73e0da225fd1c6975a52c48497532571a497ac37/src/server/incoming/mod.rs#L38-L85

**Comment by andylokandy** [comment]
Great job! However, the `MakeSpan` appears to be overly specific. 

Would you consider creating a pull request to include these changes in the repository?

**Comment by iGxnon** [comment]
Here https://github.com/tikv/minitrace-rust/pull/202

**Comment by andylokandy** [comment]
Closed by https://github.com/tikv/minitrace-rust/pull/202
