### ISSUE TITLE
WASM target support improvements

### ISSUE THREAD

**Issue by dotansimha** [tikv/minitrace-rust#203]
As a followup to https://github.com/tikv/minitrace-rust/pull/201 , I noticed an adjustment we could make to make `minitrace` more compatible with WASM runtime. 

The main issue around HTTP calls with `wasm32-unknown-unknown` is that the JS runtime (`fetch`) makes the actual HTTP call. 

This means that the exporting flow of collected traces needs to use a non-blocking, `async` HTTP client. So HTTP calls will be handled in "background" (by the JS runtime that loads the WASM), and returns a `Promise` that's being converted to `Future`. 

To address such change, I think `minitrace` can introduce an option (maybe as a feature?) to have async reporters (and `async` `flush` function). 
Also, most reporters today are using `reqwest::blocking` client, which is not available on WASM targets. 

@andylokandy  I'll be happy to make a PR to add such a feature if that makes sense.

**Comment by dotansimha** [comment]
> You can wrap an async function in the sync `report` function, by simply discarding the `Future` or storing the `Future` in a static mutex.

Yeah, but in this case, an `async` reporter might even be more useful 🤔 I can hook that into the `wait_until` (https://developers.cloudflare.com/workers/runtime-apis/handlers/fetch/#contextwaituntil) and just `await` it there without blocking anything. 

I can understand the reason for a simple, sync `report` in `minitrace`, but in this specific case it feels like a lot of workarounds are needed. 

Doing async (runtime) -> sync (Reporter) -> async (actual reporting) feels like a workaround, that can be simplified if `report` function was async 🤔

**Comment by andylokandy** [comment]
You can do: manually flushing -> save spans to be report in static/Arc -> report the spans in async context

**Comment by dotansimha** [comment]
> You can do: manually flushing -> save spans to be report to static/Arc -> report the spans in a async context

That's a great idea! I will give it a try :)

**Comment by dotansimha** [comment]
Ok, I managed to make it work! 

So basically I created a new special struct that implements Reporter. The `report` function only collects the span in memory, and I added an `async` function to do the actual reporting. I can now connect that to the rest of the setup we have. 

Thank you for the help @andylokandy , I really appreciate it!
