### ISSUE TITLE
Making `futures` an optional dependency

### ISSUE THREAD

**Issue by lhallam** [tikv/minitrace-rust#210]
Hi, I'm enjoing the simplicity of minitrace compared to tracing, but noticed it adds quite a few transitive dependencies to my projects. A large portion of these come from the `futures` crate, I assume it's only used for `FutureExt`, if so could we put it behind a feature so it can be disabled if not required?

Alternatively, I haven't checked the code yet, but maybe `futures-core` or `futures-lite` would be enough?

I'm happy to work on a PR if you're interested in either of these options.
Thanks!

**Comment by andylokandy** [comment]
`futures` seems like not being used in code lol. Welcome to contribute a PR!
