### ISSUE TITLE
does minitrace support ARM cpu?

### ISSUE THREAD

**Issue by keepsimple1** [tikv/minitrace-rust#66]
Hi, I've read your blog at https://en.pingcap.com/blog/how-we-trace-a-kv-database-with-less-than-5-percent-performance-impact .  It says x86 CPU TSC was used in this crate. How about other CPUs? Particularly, do you support ARM CPUs? I don't know if I missed it somewhere. Thanks.

**Comment by zhongzc** [comment]
minitrace-rs doesn't support other CPUs now.

**Comment by keepsimple1** [comment]
Thanks for your answer!
