### ISSUE TITLE
dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by breeswish** [tikv/minitrace-rust#82]
https://github.com/tikv/minitrace-rust/blob/master/CONTRIBUTING.md points to a dead link.

**Comment by Xuanwo** [comment]
Since it's a project under tikv org, how about copying and adapting from https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md as CONTRIBUTING.md?

I'm willing to submit a PR for it.

**Comment by breeswish** [comment]
@Xuanwo The TiKV's contribution guide describes how to build TiKV. It is verbose but seems to be not helpful to engage in the minitrace. Do you have some suggestions?

**Comment by Xuanwo** [comment]
I think `opendal`'s contributing guide is more suiteable for `minitrace`, which is a lib too, please take a look https://github.com/datafuselabs/opendal/blob/main/CONTRIBUTING.md

**Comment by breeswish** [comment]
@Xuanwo Looks cool, please go ahead!
