### ISSUE TITLE
Improve the README for both GitHub and docs.rs

### ISSUE THREAD

**Issue by breezewish** [tikv/minitrace-rust#89]
There are some typical usages of a tracing library. One may be interested in the following examples (comments are welcome!):

- [ ] Basic (multiple function spans) - an implicit style can be involed.
- [ ] Macro shortcut - use macros to make life easier.
- [ ] Async - We are in year 2022 now. Async is the new standard.
- [ ] Send spans across threads - This is less common compared to async in year 2022.
- [ ] Other Advanced Usages

**Comment by andylokandy** [comment]
Maybe the content in lib.rs has fulfilled the topics you mentioned: https://docs.rs/minitrace/0.4.0/minitrace/
